
CSV_PATH = 'data/'
LIGNAN_URIN_PATH = CSV_PATH + 'test.csv'
NUTRITION_PATH = CSV_PATH + 'nutrition.csv'
LIGNAN_PLASMA_PATH = CSV_PATH + '140305_Lignans_HH_plasma.csv'
BLOOD_LIPID_PATH = CSV_PATH + '140304_blood_lipids.csv'
OTU_PATH = CSV_PATH + 'otu_table_mc2_s2_00001.txt'
SCFA_DRY_PATH = CSV_PATH + '140304_SCFA_dry.csv'
SCFA_WET_PATH = CSV_PATH + '140304_SCFA_wet.csv'

TEST_PERSONS = 9*5
LIGNANS = 4